export const pricingPlans = [
  {
    tier: 'economy' as const,
    name: 'Economy',
    price: '$99',
    subtitle: 'Quick refresh - look great, spend less',
    features: [
      'Exterior hand wash & rinse',
      'Interior vacuum (seats, floors & trunk)',
      'Interior wipe-down & dashboard clean',
      'Rim cleaning',
      'Tire shine',
      'Spray wax coat',
      'Complimentary gift box',
    ],
  },
  {
    tier: 'silver' as const,
    name: 'Silver',
    price: '$179',
    subtitle: 'Deep cleaning - inside and out',
    features: [
      'Exterior hand wash & rinse',
      'Deep interior vacuum (including crevices)',
      'Deep rim cleaning',
      'Tire shine',
      'Spray wax coat',
      'Deep interior detailing',
      'Shampoo floor mats',
      'Plastic conditioning & trim care',
      'Complimentary gift box',
    ],
    highlightedFeatures: ['Deep interior detailing', 'Shampoo floor mats', 'Plastic conditioning & trim care'],
  },
  {
    tier: 'gold' as const,
    name: 'Gold',
    price: '$249',
    subtitle: 'Premium transformation & protection',
    features: [
      'Exterior hand wash & rinse',
      'Full interior vacuum',
      'Full rim cleaning',
      'Tire shine',
      'Shampoo floor mats',
      'Plastic conditioning & trim care',
      'Full interior detailing (seats, carpets, panels & vents)',
      'Steam cleaning of all high-touch areas',
      'Leather & cloth conditioning',
      'Pet hair removal',
      'Odor elimination treatment',
      'Premium hand wax',
      'Complimentary gift box',
    ],
    highlightedFeatures: [
      'Full interior detailing (seats, carpets, panels & vents)',
      'Steam cleaning of all high-touch areas',
      'Leather & cloth conditioning',
      'Pet hair removal',
      'Odor elimination treatment',
      'Premium hand wax',
    ],
  },
]
