export const pricingPlans = [
  {
    tier: 'economy' as const,
    name: 'Economy',
    price: '$109',
    subtitle: 'Essential care for everyday drivers',
    features: [
      'Exterior hand wash & rinse',
      'Window cleaning (interior & exterior)',
      'Tire & rim scrub',
      'Interior vacuum (seats, carpets, trunk)',
      'Dashboard & console wipe-down',
      'Door jambs & sill cleaning',
      'Air freshener',
    ],
  },
  {
    tier: 'silver' as const,
    name: 'Silver',
    price: '$179',
    subtitle: 'Full detail — inside and out',
    features: [
      'Exterior hand wash & rinse',
      'Window cleaning (interior & exterior)',
      'Tire & rim scrub',
      'Interior vacuum (seats, carpets, trunk)',
      'Dashboard & console wipe-down',
      'Door jambs & sill cleaning',
      'Air freshener',
      'Full interior deep clean',
      'Seat & carpet hot-water extraction',
      'Door panels & headliner detail',
      'Leather/vinyl conditioning',
      'Trunk full detail',
      'Tire dressing & shine',
      'Exterior spray wax',
    ],
  },
  {
    tier: 'gold' as const,
    name: 'Gold',
    price: '$279',
    subtitle: 'Premium transformation & protection',
    features: [
      'Exterior hand wash & rinse',
      'Window cleaning (interior & exterior)',
      'Tire & rim scrub',
      'Interior vacuum (seats, carpets, trunk)',
      'Dashboard & console wipe-down',
      'Door jambs & sill cleaning',
      'Air freshener',
      'Full interior deep clean',
      'Seat & carpet hot-water extraction',
      'Door panels & headliner detail',
      'Leather/vinyl conditioning',
      'Trunk full detail',
      'Tire dressing & shine',
      'Exterior spray wax',
      'Clay bar paint decontamination',
      'Machine polish & swirl removal',
      'Hand wax & paint sealant',
      'Deep leather conditioning & protection',
      'Headlight restoration',
      'Exterior plastic trim restoration',
      'Premium branded gift included',
    ],
  },
]
